FROM python:3.10-alpine
LABEL maintainer="maxime.bellet@orange.com"

RUN apk update && apk add git
WORKDIR /usr/src/app
RUN python3 -m venv venv

WORKDIR /usr/src/app/venv/

# clone gitlabs dep projects.
#
# RUN git clone URL_librairie &&\
#     git clone URL_automate_py &&\
#     git clone URL_dependances &&\
#     chmod +x URL_dependances/script/prepare.sh && \
#     /URL_dependances/script/prepare.sh


ENV ENV_AUTO_PROD="production"
ENV CUID = "none"


WORKDIR  /usr/src/app/
