FROM python:3.10-alpine
LABEL maintainer="maxime.bellet@orange.com"

RUN apk update && apk add git
WORKDIR /usr/src/app
RUN python3 -m venv venv

WORKDIR /usr/src/app/venv/

# clone gitlabs dep projects.
#
RUN git clone https://gitlab.tech.orange/automatisation-rtc/URL_librairie &&\
    git clone https://gitlab.tech.orange/automatisation-rtc/URL_automate_py &&\
    git clone https://gitlab.tech.orange/automatisation-rtc/URL_dependances &&\
    chmod +x URL_dependances/script/prepare.sh && \
    /URL_dependances/script/prepare.sh


WORKDIR  /usr/src/app/
